name: Docker Build and Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        # registry: # optional
        repository: mtrense/psql-tools
        # tags: # optional
        tag_with_ref: true
        tag_with_sha: true
        # path: # optional, default is .
        # dockerfile: 
        # target:
        # always_pull:
        # build_args: # optional
        # cache_froms: # optional
        # labels: # optional
        add_git_labels: true
        push: true
